id: IC89F8419
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:52:31+00:00'
last_modified: '2022-06-09T08:20:43.005690+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16784
  title: ཁམས་ཆེན་པོ་བརྒྱད་དང་མཚོན་བྱེད་ཞེ་ལྔའི་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    979C:
      image_group_id: I8LS16795
      title: Volume 1 of khams chen po brgyad dang mtshon byed zhe lnga'i rnam gzhag
      total_pages: 40
      order: 1
      base_file: 979C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
