id: P007987
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:32.263683
source_metadata:
  id: bdr:W8LS16784
  title: ཁམས་ཆེན་པོ་བརྒྱད་དང་མཚོན་བྱེད་ཞེ་ལྔའི་རྣམ་གཞག
  author: ''
  volumes:
    1f904bf34b87411b83f0951c05778a79:
      image_group_id: I8LS16795
      title: Volume 1 of khams chen po brgyad dang mtshon byed zhe lnga'i rnam gzhag
      volume_number: 1
      total_pages: 40
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
