id: P007987
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16784
  title: ཁམས་ཆེན་པོ་བརྒྱད་དང་མཚོན་བྱེད་ཞེ་ལྔའི་རྣམ་གཞག
  author: ''
  volumes:
    cf63e2bec63c4bacaf310835a26c7071:
      image_group_id: I8LS16795
      title: ''
      volume_number: 1
      total_pages: 40
ebook_metadata:
  title: ཁམས་ཆེན་པོ་བརྒྱད་དང་མཚོན་བྱེད་ཞེ་ལྔའི་རྣམ་གཞག
  author: ''
  sku: P007987
  cover: cover.jpg
  layers:
  - pagination
